### ISSUE TITLE
Chapter 9　テスト

### ISSUE THREAD

**Issue by MofuMofu2** [MofuMofu2/react-sandbox#48]
前半はJestとテストの基本だったのでスキップ

**Comment by MofuMofu2** [comment]
要素の取得を行うAPI = クエリメソッドという。
https://testing-library.com/docs/queries/about

**Comment by MofuMofu2** [comment]
roleで取得できるが、テストのためにroleを無理やりつけるのはNG。この前の勉強会でも言っていた。
違うroleをつけてしまうと本当に必要な人が困ってしまう。

**Comment by MofuMofu2** [comment]
pointer / keybordメソッドを使うとポインターやキーのクリックを詳細に指定できる。

**Comment by MofuMofu2** [comment]
Vue.jsと違って子コンポーネントまでアクセスしたくない場合は「コンポーネントモック」を使う。
でもモックを多用すると実操作と離れてくるのであまり意味がなさそうと思ってしまう 🤔

**Comment by MofuMofu2** [comment]
msw の部分はv2になって古くなってしまった…こういうのがあると辛いよな 😭 

https://mswjs.io/docs/migrations/1.x-to-2.x/

**Comment by MofuMofu2** [comment]
mswのモックを使ってテストを書いたらReferenceError: TextEncoder is not definedと出てきた。

これはmswhandlers.tsでhttpのモックを使おうとしているが、httpはブラウザでしか使えないAPIである[TextEncoder](https://developer.mozilla.org/ja/docs/Web/API/TextEncoder)を使っているため。

テストはNode.js環境で動くため、実質テスト用にもう一度セットアップ関数を書かないといけない。
再利用できないってことなので、なんか退化した気もする。環境が違うからAPIをきちんと区別して合わせましたということだろうか。

https://mswjs.io/docs/integrations/node

<details><summary>落ちたテスト</summary>
<p>

```typescript
mofumofu at mofunoMacBook-Air in ~/git/react-sandbox (chapter-9●●)
$ npm run test src/component/Query/QuerySample.test.tsx

> reactjs-sandbox@1.0.0 test
> react-scripts test --watchAll=false src/component/Query/QuerySample.test.tsx

 FAIL  src/component/Query/QuerySample.test.tsx
  ● Test suite failed to run

    ReferenceError: TextEncoder is not defined

    > 1 | import { setupServer } from "msw/node";
        | ^
      2 | import { handlers } from "./handlers";
      3 |
      4 | export const server = setupServer(...handlers);

      at Object.<anonymous> (node_modules/@mswjs/interceptors/lib/node/chunk-3LFH2WCF.js:2:15)
      at Object.<anonymous> (node_modules/@mswjs/interceptors/lib/node/index.js:7:24)
      at Object.<anonymous> (node_modules/msw/lib/node/index.js:49:27)
      at Object.<anonymous> (src/mocks/server.ts:1:1)
      at Object.<anonymous> (src/component/Query/QuerySample.test.tsx:3:1)
      at TestScheduler.scheduleTests (node_modules/react-scripts/node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/react-scripts/node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/react-scripts/node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/react-scripts/node_modules/@jest/core/build/cli/index.js:173:3)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.107 s
Ran all test suites matching /src\/component\/Query\/QuerySample.test.tsx/i.
``` 


</p>
</details>

**Comment by MofuMofu2** [comment]
切り分けのためhandler.tsからのインポートをやめたところ、今度はHttpResponseが解釈できずに落ちる。
ビルドツールのインポート /  エクスポートか？エディタでジャンプできるのでパスの解釈は正しいと思うが。

<details><summary>インポートで落ちる</summary>
<p>

```
 npm run test src/component/Query/QuerySample.test.tsx

> reactjs-sandbox@1.0.0 test
> react-scripts test --watchAll=false src/component/Query/QuerySample.test.tsx

 FAIL  src/component/Query/QuerySample.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/mofumofu/git/react-sandbox/node_modules/@bundled-es-modules/statuses/index-esm.js:172
    export {
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      2 | import { render } from "@testing-library/react";
      3 | import QuerySample from "./QuerySample";
    > 4 | import { http, HttpResponse } from "msw";
        | ^
      5 | import { setupServer } from "msw/node";
      6 |
      7 | describe("APIレスポンスパラメータの取得状態に応じてレンダリング結果が変わること", () => {

      at Runtime.createScriptFromCode (node_modules/react-scripts/node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/msw/lib/core/utils/logging/serializeResponse.js:54:31)
      at Object.<anonymous> (node_modules/msw/lib/core/handlers/HttpHandler.js:50:32)
      at Object.<anonymous> (node_modules/msw/lib/core/http.js:24:26)
      at Object.<anonymous> (node_modules/msw/lib/core/index.js:38:19)
      at Object.<anonymous> (src/component/Query/QuerySample.test.tsx:4:1)
      at TestScheduler.scheduleTests (node_modules/react-scripts/node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/react-scripts/node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/react-scripts/node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/react-scripts/node_modules/@jest/core/build/cli/index.js:173:3)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.154 s
Ran all test suites matching /src\/component\/Query\/QuerySample.test.tsx/i.
``` 

</p>
</details>

**Comment by MofuMofu2** [comment]
書籍だとmsw1.xとCreact React Appを使っている。どちらも古くなってしまっている。

1. msw2.xで依存しているAPIがNode.jsのAPIだけど、Jestではこれが読み込めない
2. 補うためのコードpolyfillsを作ってねとあるが、Create React AppではsetupFilesオプションを上書きできずpolyfilが使えない
3. msw2.xを使うならCreate React Appをやめないとだめ。終わり 😭 みたいになる

やっぱりバンドラーツールが古いとこういうときに影響が出るなと思った。頑張ってViteにするしかないか。

https://mswjs.io/docs/migrations/1.x-to-2.x#requestresponsetextencoder-is-not-defined-jest

<details><summary>出てくるエラー</summary>
<p>

```
Out of the box, Create React App only supports overriding these Jest options:

  • clearMocks
  • collectCoverageFrom
  • coveragePathIgnorePatterns
  • coverageReporters
  • coverageThreshold
  • displayName
  • extraGlobals
  • globalSetup
  • globalTeardown
  • moduleNameMapper
  • resetMocks
  • resetModules
  • restoreMocks
  • snapshotSerializers
  • testMatch
  • transform
  • transformIgnorePatterns
  • watchPathIgnorePatterns.
```

</p>
</details>
