### ISSUE TITLE
MDXを試す

### ISSUE THREAD

**Issue by MofuMofu2** [MofuMofu2/react-sandbox#6]
コンポーネント内にMarkdownを差し込める（逆か？）[MDX](https://mdxjs.com/)を使ってみる。
MDXはMarkdown + JSXなので、ブログやドキュメントを記載する際、Markdownの中にJSXコンポーネントを差し込める。

実装後の例を出す際などにとても便利 + コンポーネントライブラリをそのまま使えるので良さそう。

- https://mdxjs.com/docs/getting-started/#jsx
- https://zenn.dev/spring_raining/articles/3eb62ff93df1eb
- https://raykeymas.com/posts/nextjs/nextjs-mdx

**Comment by MofuMofu2** [comment]
インストール

1. [bundler](https://mdxjs.com/docs/getting-started/#bundler)用ツールのインストール
2. [ライブラリ](https://mdxjs.com/docs/getting-started/#jsx)のインストール
3. [TypeScript用types](https://mdxjs.com/docs/getting-started/#types)のインストール

**Comment by MofuMofu2** [comment]
Expand Exampleを参考に`mdx`を置いてみたが、tag nameの名前解決ができていない様子。
https://mdxjs.com/docs/getting-started/#create-react-app-cra

```markdown
Unhandled Thrown Error!
Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/content.e417dbbe17c284a8b0c5.mdx') is not a valid name.
Error: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/content.e417dbbe17c284a8b0c5.mdx') is not a valid name.
    at createElement (http://localhost:3000/static/js/bundle.js:19147:38)
    at createInstance (http://localhost:3000/static/js/bundle.js:20136:24)
    at completeWork (http://localhost:3000/static/js/bundle.js:29756:32)
    at completeUnitOfWork (http://localhost:3000/static/js/bundle.js:33518:20)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:33494:9)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:33408:9)
    at renderRootSync (http://localhost:3000/static/js/bundle.js:33381:11)
    at recoverFromConcurrentError (http://localhost:3000/static/js/bundle.js:32873:24)
    at performConcurrentWorkOnRoot (http://localhost:3000/static/js/bundle.js:32785:26)
    at workLoop (http://localhost:3000/static/js/bundle.js:43088:38)
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own errorElement props on <Route>
```

**Comment by MofuMofu2** [comment]
https://github.com/MofuMofu2/react-sandbox/issues/6#issuecomment-1370430371

Create React App側のwebpack.config.jsの設定にMDXの設定が含まれておらず、その結果名前解決ができていない様子。
※CRAはCreate React Appのこと。

CRAの設定を上書きする[CRACO](https://github.com/dilanx/craco)を利用すれば回避はできる。
https://mdxjs.com/docs/getting-started/#create-react-app-cra
